import Testing
import Year2024

struct Day08Tests {
    let data = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    @Test
    func part1() async throws {
        let day = Day08(data: data)

        let part1 = try await day.part1()
        #expect(part1 == 14)
    }

    @Test
    func part2() async throws {
        let day = Day08(data: data)

        let part2 = try await day.part2()
        #expect(part2 == 34)
    }
}
